### ISSUE TITLE
It doesn't work :/

### ISSUE THREAD

**Issue by tobiashochguertel** [unlight/sublime-markdown-link#10]
I just found the plugin a few minute ago, and tried it out but it doesn't work here at my MacBook in Sublime 3. I looked into the console of Sublime, and can't find any error or log messages which gives me a hint where an why it fails or doesn't work.

Can you give me some advices how I can get some logs about why it does not work here at my machine?

![image](https://user-images.githubusercontent.com/3332669/101807967-08ecfb80-3b16-11eb-84f0-74035f7f6016.png)
![image](https://user-images.githubusercontent.com/3332669/101808039-1d30f880-3b16-11eb-86eb-8d19309936d4.png)

![image](https://user-images.githubusercontent.com/3332669/101808148-40f43e80-3b16-11eb-8ec3-5b2a8eec0648.png)

**Comment by unlight** [comment]
Hi, @tobiashochguertel 

Few questions.
1. Did you selected several lines in single selection? If yes, then it is not right. You should do multiple selection of each line (Palette -> Selection: Split Into Lines - Ctrl + Shift + L)
2. Did selection(s) include dash at the start of the string? If yes, it's treated as not valid URL. Should be considered as bug.

Try to on simple line - http://example.com/
Also note, that plugin is making changes synchronously, so big list can freeze ST for along time.

**Comment by tobiashochguertel** [comment]
![image](https://user-images.githubusercontent.com/3332669/101817436-aea66780-3b22-11eb-8d5e-7f1dcca3f359.png)

I did some tests... and hope that this helps:

```





# Hello World!

- http://www.google.de
- http://www.google.de
- http://www.google.de



https://www.google.de

- https://www.google.de/

https://www.google.de

- http://example.com/

- http://example.com/


- http://example.com/
- [Example Domain](http://example.com)



http://example.com/
[Example Domain](http://example.com/)
```

**Works:**

Selecting: `http://example.com/` an using `MarkdownLink` works.
![image](https://user-images.githubusercontent.com/3332669/101817745-22487480-3b23-11eb-8bd1-00b382877441.png)

also when in a list, by selecting only the url:
![image](https://user-images.githubusercontent.com/3332669/101817791-32f8ea80-3b23-11eb-9660-22466dc9a69a.png)

also when selecting with a space at the beginning it works:
![image](https://user-images.githubusercontent.com/3332669/101817841-4b690500-3b23-11eb-8db3-06972458b0b4.png)


What I got working is also `http://example.de`with **`http`** but with **`https`** it does not work:

![image](https://user-images.githubusercontent.com/3332669/101818582-5f613680-3b24-11eb-97bb-15340cb4ec4b.png)

**Works not:**

Selecting with the starting `-` does not work: 
![image](https://user-images.githubusercontent.com/3332669/101817725-1957a300-3b23-11eb-9fe5-82461f44ce35.png)

Also with different urls like: `google.de` I can't get it working:

![image](https://user-images.githubusercontent.com/3332669/101817888-6176c580-3b23-11eb-8b8d-5735f66cb396.png)

![image](https://user-images.githubusercontent.com/3332669/101817971-81a68480-3b23-11eb-8500-90caa525d58f.png)

![image](https://user-images.githubusercontent.com/3332669/101817999-89febf80-3b23-11eb-838e-b57edc04ac74.png)

![image](https://user-images.githubusercontent.com/3332669/101818033-93882780-3b23-11eb-9619-2f7cfd201bfd.png)

![image](https://user-images.githubusercontent.com/3332669/101818049-98e57200-3b23-11eb-9e3e-6213fafefc73.png)

![image](https://user-images.githubusercontent.com/3332669/101818062-9e42bc80-3b23-11eb-82a9-7926d7bee1b6.png)

![image](https://user-images.githubusercontent.com/3332669/101818141-bfa3a880-3b23-11eb-9992-a20e68287737.png)

![image](https://user-images.githubusercontent.com/3332669/101818359-0396ad80-3b24-11eb-91a9-e7e02a245031.png)

![image](https://user-images.githubusercontent.com/3332669/101818414-1dd08b80-3b24-11eb-8e7d-1a35ca24cfc9.png)


Also with these selection as "With Split into Lines":

![image](https://user-images.githubusercontent.com/3332669/101818234-dcd87700-3b23-11eb-87aa-ba40d9a332dc.png)


---

My Playgorund:
```




# Hello World!

- http://www.google.de
- http://www.google.de
- http://www.google.de


- http://www.google.de/asas
- https://www.google.de
- http://www.google.de/
- http://example.com/
- https://example.com/
- https://example.de

- http://www.google.de/asas
- https://www.google.de
- http://www.google.de/
- http://example.com/
- [Example Domain](https://example.com/)
- https://example.de


- http://www.google.de/asas
- https://www.google.de
- http://www.google.de/
- http://example.com/
- https://example.com/
- http://example.de


- http://www.google.de/asas
- https://www.google.de
- http://www.google.de/
- http://example.com/
- https://example.com/
- [3erlei.de](http://example.de)








https://www.google.de



- https://www.google.de/



https://www.google.de

- http://example.com/

- http://example.com/



- http://example.com/
-[Example Domain]( http://example.com/)


- http://example.com/
- [Example Domain](http://example.com)



http://example.com/
[Example Domain](http://example.com/)
```

**Comment by unlight** [comment]
As I said, `- http://example.com/` is not valid URL. There is a room for improvement. Also, for some sites title is not detecting well.

**Comment by tobiashochguertel** [comment]
yes okay, that with "- http://" does not work is okay. Thanks for the explanation. I would take this as a feature request.

An also a feature request from my perspective would be when we can get some feedback about the urls which are not transformed because of the title isn't figured out - any feedback when the transformation fails would be great.

I like the plugin's idea.

**Comment by tobiashochguertel** [comment]
> As I said, `- http://example.com/` is not valid URL. There is a room for improvement. Also, for some sites title is not detecting well.

Ah! forgotten to tell, that I read that also before, and add it as an wish and for quick have some test cases for this feature.

**Comment by unlight** [comment]
I decided to not make an improvement related to "list style urls", because it will complicate parsing and string manipulation.

Instead I suggest to use "Select URIs from cursors" or "Select URIs from the current view
" command from [OpenUri](https://packagecontrol.io/packages/OpenUri) plugin then "Make link from URL" by sublime-markdown-link

Other improvement show error in console will be added.

**Comment by pqnhan** [comment]
Hi, I just installed the Plugin and tried on some links but it doesn't seem to work.

For example `https://i.imgur.com/nlXRWag.jpeg`, I tried to convert some of my pictures like that but it didn't work.

--
Update:
It doesn't seem to work with the `https` protocol and neither does when I use sublime offline.
